// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.ChoiceAliases.Choice(Cake.Core.ICakeContext,System.String[])~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.ChoiceAliases.Choice(Cake.Core.ICakeContext,System.String[],System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Checked", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.GetAllArgumentsAliases.GetArgumentsDictionary(Cake.Core.ICakeArguments)~System.Collections.Generic.Dictionary{System.String,System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.ConfigureParameterAliases.ConfigureRequiredParameter``1(Cake.Core.ICakeContext,System.String)~System.Func{System.String,``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.ConfigureParameterAliases.ConfigureParameterWithDefaultValue``1(Cake.Core.ICakeContext,System.String)~System.Func{System.String,``0,``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.ParameterAliases.Parameter``1(Cake.Core.ICakeContext,System.String)~``0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.ParameterAliases.Parameter``1(Cake.Core.ICakeContext,System.String,``0)~``0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.GetAllArgumentsAliases.GetAllArguments(Cake.Core.ICakeContext,System.Boolean)~System.Collections.Generic.IDictionary{System.String,System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Validated", Scope = "member", Target = "~M:CakeToolBox.Parameters.Aliases.GetAllArgumentsAliases.GetAllArgumentsNames(Cake.Core.ICakeContext,System.Boolean)~System.Collections.Generic.IEnumerable{System.String}")]
