name: CakeToolBox Publish

on:
  push:
    tags:
       - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Build and publish packages on nuget
      uses: actions/checkout@v2

    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      env:
        NUGET_API_KEY: ${{ secrets.NugetApiKey }}
        GITHUB_API_KEY: ${{ secrets.GitHubApiKey }}
      with:
        verbosity: Verbose
        target: Publish
