name: CakeToolBox Publish

on:
  push:
    tags:
       - '*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publich packages on nuget
      uses: ecampidoglio/cake-action@v1.1.1
      env:
        NUGET_API_KEY: ${{ secrets.NugetApiKey }}
      with:
        target: Publish
        verbosity: Diagnostic
