name: CakeToolBox Publish

on:
  push:
    tags:
       - '*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish packages on nuget
      env:
        NUGET_API_KEY: ${{ secrets.NugetApiKey }}
      run: ./build.ps1 -Target Publish
      shell: powershell