name: CakeToolBox Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test packages
      uses: cake-build/cake-action@v1
      with:
        verbosity: Verbose
        target: Test
